version: '2'

services:
  rust-sgx:
    image: flieske/gramine-rust:latest
    container_name: "gramine-sgx"
    build:
      context: .
      args:
        - projectName=hello_world
        - webFiles=web_files
    ports:
      - "80:80"
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
    stdin_open: true              # docker run -i
    tty: true                     # docker run -t